#ifndef CLARABEL_H
#define CLARABEL_H

/* Generated with cbindgen:0.24.5 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 * This file is only used to track the changes in the Rust wrapper.
 * Use the headers in ../../include instead.
 */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace clarabel {

enum class DirectSolveMethods {
  QDLDL,
  MKL,
  CHOLMOD,
};

template<typename T>
struct CscMatrix {
  uintptr_t m;
  uintptr_t n;
  const uintptr_t *colptr;
  const uintptr_t *rowval;
  const T *nzval;
  bool owns_matrix_data;
};

template<typename T>
struct DefaultSettings {
  uint32_t max_iter;
  double time_limit;
  bool verbose;
  T max_step_fraction;
  T tol_gap_abs;
  T tol_gap_rel;
  T tol_feas;
  T tol_infeas_abs;
  T tol_infeas_rel;
  T tol_ktratio;
  T reduced_tol_gap_abs;
  T reduced_tol_gap_rel;
  T reduced_tol_feas;
  T reduced_tol_infeas_abs;
  T reduced_tol_infeas_rel;
  T reduced_tol_ktratio;
  bool equilibrate_enable;
  uint32_t equilibrate_max_iter;
  T equilibrate_min_scaling;
  T equilibrate_max_scaling;
  T linesearch_backtrack_step;
  T min_switch_step_length;
  T min_terminate_step_length;
  bool direct_kkt_solver;
  DirectSolveMethods direct_solve_method;
  bool static_regularization_enable;
  T static_regularization_constant;
  T static_regularization_proportional;
  bool dynamic_regularization_enable;
  T dynamic_regularization_eps;
  T dynamic_regularization_delta;
  bool iterative_refinement_enable;
  T iterative_refinement_reltol;
  T iterative_refinement_abstol;
  uint32_t iterative_refinement_max_iter;
  T iterative_refinement_stop_ratio;
  bool presolve_enable;
};

using DefaultSolver = void;

template<typename T>
struct SupportedConeT {
  enum class Tag {
    ZeroConeT,
    NonnegativeConeT,
    SecondOrderConeT,
    ExponentialConeT,
    PowerConeT,
  };

  struct ZeroConeT_Body {
    uintptr_t _0;
  };

  struct NonnegativeConeT_Body {
    uintptr_t _0;
  };

  struct SecondOrderConeT_Body {
    uintptr_t _0;
  };

  struct ExponentialConeT_Body {

  };

  struct PowerConeT_Body {
    T _0;
  };

  Tag tag;
  union {
    ZeroConeT_Body zero_cone_t;
    NonnegativeConeT_Body nonnegative_cone_t;
    SecondOrderConeT_Body second_order_cone_t;
    ExponentialConeT_Body exponential_cone_t;
    PowerConeT_Body power_cone_t;
  };
};

extern "C" {

CscMatrix<double> *CscMatrix_f64_from(uintptr_t m, uintptr_t n, const double *matrix);

CscMatrix<double> *CscMatrix_f64_zeros(uintptr_t rows, uintptr_t cols);

CscMatrix<double> *CscMatrix_f64_identity(uintptr_t n);

void delete_CscMatrix_f64(CscMatrix<double> *matrix);

DefaultSettings<double> DefaultSettingsBuilder_f64_default();

DefaultSolver *DefaultSolver_f64_new(const CscMatrix<double> *P,
                                     const double *q,
                                     const CscMatrix<double> *A,
                                     const double *b,
                                     uintptr_t n_cones,
                                     const SupportedConeT<double> *cones,
                                     const DefaultSettings<double> *settings);

void DefaultSolver_solve(DefaultSolver *solver);

void free_DefaultSolver(DefaultSolver *solver);

} // extern "C"

} // namespace clarabel

#endif // CLARABEL_H
